// <auto-generated>
// Rewired Constants
// This list was generated on 2021/1/11 10:53:10
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "CursorUp")]
        public const int CursorUp = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "CursorDown")]
        public const int CursorDown = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action2")]
        public const int CursorLeft = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "CursorRight")]
        public const int CursorRight = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "BossPause")]
        public const int BossPause = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveUnit")]
        public const int MoveUnit = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "RotateUnit")]
        public const int RotateUnit = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "HintHDD")]
        public const int HintHDD = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "HintNetwork")]
        public const int HintNetwork = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "HintControl")]
        public const int HintControl = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "CycleNext")]
        public const int CycleNext = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func0")]
        public const int Func0 = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func1")]
        public const int Func1 = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func2")]
        public const int Func2 = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func3")]
        public const int Func3 = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func4")]
        public const int Func4 = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func5")]
        public const int Func5 = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func6")]
        public const int Func6 = 18;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func7")]
        public const int Func7 = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func8")]
        public const int Func8 = 20;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Func9")]
        public const int Func9 = 21;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Confirm")]
        public const int Confirm0 = 22;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
